artifacts_dir: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "koushik7198/Samsung-samsum_processed"
  local_data_file: "artifacts/data_ingestion/Samsung-samsum" 
data_transformation:
  root_dir: "artifacts/data_transformation"
  data_path: "artifacts/data_ingestion/Samsung-samsum"
  tokenizer_name: "google/pegasus-cnn_dailymail"
model_training:
  root_dir: "s3://amzn-s3-llm-bucket/SmartSummarizer/model"
  data_dir: "artifacts/data_transformation/Samsung-samsum-transformed"
  model_name: "google/pegasus-cnn_dailymail"
model_evaluation:
  root_dir: "s3://amzn-s3-llm-bucket/SmartSummarizer/model"
  model_dir: "artifacts/model_evaluation/model/pegasus-model"
  tokenizer_dir: "artifacts/model_evaluation/model/tokenizer"
  data_path: artifacts/data_transformation/Samsung-samsum-transformed/test
  metric_file_name: artifacts/model_evaluation/metric.csv